### PR TITLE
add dockerfile for api

### PR DESCRIPTION
**Pull request by dpopp07**
@jamesvclements Just making this PR so you can test this out for yourself. Will post instructions in this PR soon

Don't merge this yet.

todo:
- [x] Make sure this dockerfile is actually what i want
- [x] Add CI support for deploying this bad boi
- [x] Dockerfile shouldn't count for code coverage numbers

**Instructions for Running Locally**
- Install [Docker](https://www.docker.com/community-edition) on your machine
- Pull down the official rethinkdb image: `docker pull rethinkdb`
- Run the rethink docker container: `docker run -p 8080:8080 --name <name> -v "$PWD:/data" -d rethinkdb`
  - <name> can be whatever, I used "bartop-dev"
- Go to localhost:8080 and use the rethink web ui to create a database called `bartop_dev`. The API expects that exact name
- Run `docker inspect --format '{{ .NetworkSettings.IPAddress }} <name>' to get the IP address of the rethink container
- Add that IP address to the `.env` file for the API under the key `BARTOP_DB_HOST`
- In the `bartop-api/` folder, build the image by running `docker build -t <docker-username>/<registry-tag> .`
  - <registry-tag> can be whatever you want. I used "bartop-api"
- Build the API container `docker run -p 49160:3001 --name bartop-api -d <docker-username>/<registry-tag>`

The API should now be available at `localhost:49160/api/`

**Troubleshooting**
`docker ps` shows the list of running containers and their IDs
`docker logs <id>` shows the output of the container, helpful for debugging

### CODE REVIEW

**Comment by jamesvclements** [comment]
We should add all these `docker` commands as `scripts` in the `package.json`

**Comment by dpopp07** [comment]
Yeah I'm gonna need to see what we need to do for deploying. Some of those commands are user-specific so maybe not ideal for package.json

**Comment by dpopp07** [comment]
This is good to go as far as being reviewed, won't know if it works until we merge tho 🤷‍♀️

**Review by jamesvclements — APPROVED** [review]
baby out the nest

**Pull request merged**
